title: onnoo's backlog
email: sweyjw@gmail.com
description: >-
  A personal blog hosted on GitHub Pages using Jekyll.
  Write your site description here.
baseurl: ""
url: "https://onnoo.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins: []

# GitHub Pages settings
repository: onnoo/onnoo.github.io

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include admin folder for Decap CMS
include:
  - admin